package vn.iotstar.service.impl;
import vn.iotstar.config.StorageProperties; import vn.iotstar.exception.StorageException; import vn.iotstar.service.IStorageService; import org.springframework.core.io.*; import org.springframework.stereotype.Service; import org.springframework.web.multipart.MultipartFile; import java.io.*; import java.nio.file.*; import java.util.*;
@Service public class FileSystemStorageService implements IStorageService {
 private final Path root; private final long max; private static final Set<String> EXT=Set.of("png","jpg","jpeg","gif","webp");
 public FileSystemStorageService(StorageProperties p){root=Path.of(p.getLocation()).toAbsolutePath().normalize();max=p.getMaxFileSize(); try{Files.createDirectories(root);}catch(IOException e){throw new StorageException("Không thể khởi tạo thư mục upload",e);}}
 public String store(MultipartFile f){if(f==null||f.isEmpty())throw new StorageException("Tệp tải lên không được rỗng");if(f.getSize()>max)throw new StorageException("Tệp vượt quá kích thước cho phép");String original=Optional.ofNullable(f.getOriginalFilename()).orElse("");String ext=original.lastIndexOf('.')<0?"":original.substring(original.lastIndexOf('.')+1).toLowerCase(Locale.ROOT);if(!EXT.contains(ext)||f.getContentType()==null||!f.getContentType().toLowerCase(Locale.ROOT).startsWith("image/"))throw new StorageException("Chỉ chấp nhận ảnh PNG, JPG, GIF hoặc WEBP");String n=UUID.randomUUID()+"."+ext;try(InputStream in=f.getInputStream()){Files.copy(in,resolve(n),StandardCopyOption.REPLACE_EXISTING);return n;}catch(IOException e){throw new StorageException("Không thể lưu tệp",e);}}
 public Resource loadAsResource(String name){try{Resource r=new UrlResource(resolve(name).toUri());if(r.exists()&&r.isReadable())return r;}catch(Exception ignored){}throw new StorageException("Không tìm thấy tệp");}
 public void delete(String n){if(n==null||n.isBlank())return;try{Files.deleteIfExists(resolve(n));}catch(IOException e){throw new StorageException("Không thể xóa tệp cũ",e);}}
 private Path resolve(String n){Path p=root.resolve(n).normalize();if(!p.getParent().equals(root))throw new StorageException("Tên tệp không hợp lệ");return p;}
}
