package vn.iotstar.controller;
import vn.iotstar.dto.*; import vn.iotstar.service.CategoryService; import org.springframework.data.domain.*; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.MultipartFile; import java.util.*;
@RestController @RequestMapping("/api/category") public class CategoryApiController { private final CategoryService service; public CategoryApiController(CategoryService s){service=s;}
 @GetMapping public ResponseEntity<ApiResponse<List<CategoryResponse>>> all(@RequestParam(required=false) String q){return ResponseEntity.ok(ApiResponse.ok("Lấy danh sách Category thành công",service.findAll(q)));}
 @GetMapping("/search") public ResponseEntity<ApiResponse<Page<CategoryResponse>>> search(@RequestParam(defaultValue="")String q,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="10")int size){return ResponseEntity.ok(ApiResponse.ok("Tìm kiếm thành công",service.search(q,PageRequest.of(Math.max(0,page),Math.min(Math.max(1,size),100),Sort.by("categoryName")))));}
 @PostMapping("/getCategory") public ResponseEntity<ApiResponse<CategoryResponse>> one(@RequestParam Long id){return ResponseEntity.ok(ApiResponse.ok("Lấy Category thành công",service.findById(id)));}
 @PostMapping(value="/addCategory",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) public ResponseEntity<ApiResponse<CategoryResponse>> add(@RequestParam String categoryName,@RequestPart(required=false) MultipartFile icon){return ResponseEntity.status(HttpStatus.CREATED).body(ApiResponse.ok("Thêm Category thành công",service.create(categoryName,icon)));}
 @PutMapping(value="/updateCategory",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) public ResponseEntity<ApiResponse<CategoryResponse>> update(@RequestParam Long categoryId,@RequestParam String categoryName,@RequestPart(required=false) MultipartFile icon){return ResponseEntity.ok(ApiResponse.ok("Cập nhật Category thành công",service.update(categoryId,categoryName,icon)));}
 @DeleteMapping("/deleteCategory") public ResponseEntity<ApiResponse<Void>> delete(@RequestParam Long categoryId){service.delete(categoryId);return ResponseEntity.ok(ApiResponse.ok("Xóa Category thành công",null));}}
